call plug#begin('~/.vim/plugged')
"Syntax
Plug 'rust-lang/rust.vim'
Plug 'cespare/vim-toml'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-git', { 'for': 'git' }
"UI
Plug 'altercation/vim-colors-solarized'
Plug 'bling/vim-airline'
Plug 'ryanoasis/vim-devicons'
Plug 'yggdroot/indentLine'
"Tool
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'justinmk/vim-dirvish'
Plug 'bufexplorer.zip'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ervandew/supertab'
Plug 'majutsushi/tagbar'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-unimpaired'
"dev
Plug 'scrooloose/syntastic'
Plug 'racer-rust/vim-racer'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'jreybert/vimagit'
call plug#end()

set fileencodings=utf-8,gbk,latin1
set background=dark
set t_Co=256
colo solarized
set hidden
set tabstop=4 shiftwidth=4 expandtab
set smartcase
set smartindent
if has("gui_running")
    set guioptions-=L
    set guioptions-=T
    set guioptions-=m
    set guioptions-=r
    set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 12
endif
set colorcolumn=80
" plugin settings
let g:airline_powerline_fonts = 1
let g:indentLine_char = "¦"

" rust settings
autocmd BufRead,BufNewFile Cargo.toml,Cargo.lock,*.rs compiler cargo
autocmd BufRead,BufNewFile Cargo.toml,Cargo.lock,*.rs :map <buffer> <F5> :RustRun<CR>
let g:tagbar_type_rust = {
    \ 'ctagstype' : 'rust',
    \ 'kinds' : [
        \'T:types,type definitions',
        \'f:functions,function definitions',
        \'g:enum,enumeration names',
        \'s:structure names',
        \'m:modules,module names',
        \'c:consts,static constants',
        \'t:traits,traits',
        \'i:impls,trait implementations',
    \]
    \}

nnoremap <silent> <F1> :NERDTreeToggle<CR>
nnoremap <silent> <F2> :CtrlPTag<CR>
nnoremap <silent> <F3> :CtrlPBuffer<CR>
nnoremap <silent> <F4> :CtrlPMRUFiles<CR>
nnoremap <silent> <F5> :make<CR>
nnoremap <silent> <F6> :e $MYVIMRC<CR>
nnoremap <silent> <F11> :TagbarToggle<CR>
nnoremap <silent> <F12> :NERDTreeToggle<CR>

command! CN :e ++enc=cp936
command! CU :e ++enc=utf-8
command! Cd :cd %:p:h
